version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - |
        echo "Branch name : $BRANCH_NAME"
        IMAGE_TAG="${BRANCH_NAME}"
        echo "Image tag : $IMAGE_TAG"
  build:
    commands:
      - echo "Building Docker image..."
      - |
        docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY_URI:$IMAGE_TAG $ECR_REPOSITORY_URI:latest
  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - |
        docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
        docker push $ECR_REPOSITORY_URI:latest
      - echo "Forcing ECS service redeployment..."
# manual cmd
# aws ecr --profile piercuta-dev get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/ecs/fastapi_app
# docker build -t 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/ecs/fastapi_app:staging .
# docker tag 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/ecs/fastapi_app:staging 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/ecs/fastapi_app:latest
# docker push 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/ecs/fastapi_app:staging

# aws ecr --profile piercuta-dev get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/eks/file-service
# docker build -t 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/eks/file-service:dev .
# docker tag 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/eks/file-service:dev 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/eks/file-service:latest
# docker push 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/eks/file-service:dev