apiVersion: v1
kind: Service
metadata:
  name: file-service
  labels:
    app.kubernetes.io/name: file-service
    app.kubernetes.io/component: files
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: file-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
