{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "file-service.fullname" . }}-ssm
  labels:
    {{- include "file-service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "file-service.fullname" . }}-ssm
    creationPolicy: Owner
  data:
    - secretKey: S3_BUCKET_NAME
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/files_bucket_name
    - secretKey: CLOUDFRONT_DOMAIN
      remoteRef:
        key: {{ .Values.externalSecrets.ssmPrefix }}/files_domain
{{- end }}
