apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-k8s

resources:
  - ../../base

images:
  - name: file-service
    newName: 532673134317.dkr.ecr.eu-west-1.amazonaws.com/services/eks/file-service
    newTag: dev

configMapGenerator:
  - name: file-service-config
    envs:
      - generated-file-service.env
    literals:
      - AWS_REGION=eu-west-1
    options:
      disableNameSuffixHash: true

patches:
  - path: replicas-patch.yaml
  - path: irsa-patch.yaml
